server:
  port: 8762

spring:
  application:
    name: clientdemo
    
eureka:
  client:
    register-with-eureka:  true # 表示是否注册自身到eureka服务器，
    fetch-registry: true  #fetch-registry 表示是否从eureka服务器上获取注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka
        # defaultZone就比较重要了，是设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址。
 

